likebot_private/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::group(['namespace' => 'Web', 'middleware' => ['web']], function () {

    Route::get('/', function () {
        return view('welcome');
    });
    Auth::routes();
    // Logins Auth Check login
    Route::post('/checkUsername', 'Auth\LoginController@checkUsername')->name('checkUsername');
    Route::get('/logout', 'HomeController@logout')->name('logout');

    Route::get('/home', 'HomeController@index')->name('home');

    // pricing
    Route::group(['prefix' => 'pricing', 'as' => 'pricing.'], function () {
        Route::get('', 'HomeController@pricing')->name('pricing');
        Route::post('apply', 'FactorController@applyPricing')->name('apply');
    });

    // Blog
    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
        Route::get('', 'BlogController@all')->name('all');
        Route::get('cat/{title}-{category}', 'BlogController@all')->name('category');
        Route::get('{titleId}', 'BlogController@one')->name('one');
    });

    // Auth profile
    Route::group(['prefix' => 'profile', 'middleware' => 'auth', 'as' => 'profile.'], function () {
        Route::get('', 'UserController@dashboard')->name('dashboard');

        Route::get('/dashboard', 'UserController@dashboard')->name('profile');

        // profile extension
        Route::group(['prefix' => 'extension', 'as' => 'extension.'], function () {
            Route::post('/code/create', 'UserController@extensionCodeCreate')->name('code.create');
            Route::get('/code/create', 'UserController@extensionCodeCreate')->name('code.create.get');
        });

        // profile payments
        Route::group(['prefix' => 'payments', 'as' => 'payments.'], function () {
            Route::get('', 'FactorController@payments')->name('payments');
            Route::get('callback', 'FactorController@paymentsCallback')->name('callback');
        });

        Route::group(['prefix' => 'tags', 'as' => 'tags.'], function () {
            Route::post('/edit', 'TagController@edit')->name('edit');
        });

    });

    Route::group(['prefix' => 'test'], function () {
    });

});
Route::group(['namespace' => 'Cron', 'prefix' => 'cron'], function () {
    Route::group(['prefix' => 'f90dsafsuf0fjsd9a0fsuf0700y5klvr4y8b9tqut4q8t4q270'], function () {
        Route::group(['prefix' => 'twitter'], function () {
            Route::get('/get', 'TwitterController@get');
            Route::get('/send', 'TwitterController@sendToTelegram');
        });
        Route::group(['prefix' => 'telegram'], function () {
            Route::post('/get', 'TelegramController@get');
            Route::get('/get', 'TelegramController@get');
        });
        Route::group(['prefix' => 'instagram'], function () {
            Route::get('/get', 'InstagramController@get');
            Route::get('/sendSweetVideo', 'InstagramController@sendSweetVideo');
            Route::get('/renew', 'InstagramController@renewUrls');
            Route::get('/get/tags', 'InstagramController@getTags');
            Route::get('/send/wallpaper', 'InstagramController@sendToTelegramWallpaper');
        });
    });
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['prefix' => 'telegram'], function () {
        Route::get('/sentPostsFix', 'TelegramController@sentPostsFix');
        Route::get('/all', 'TelegramController@all');
        Route::post('{telegram_post}/delete', 'TelegramController@delete');
        Route::post('{telegram_post}/active', 'TelegramController@active');
        Route::get('/fillFileNames', 'TelegramController@fillFileNames');
    });
    Route::group(['prefix' => 'instagram'], function () {
        Route::get('/fillFileNames', 'InstagramController@fillFileNames');
        Route::get('/newFileName', 'InstagramController@newFileNames');
    });
    Route::group(['prefix' => 'tests'], function () {
        Route::get('/all', 'TelegramController@tests');
    });
});

likebot_private/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

likebot_private/resources/views/payment-callback.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <div class="row">
            <div class="main_home">
                <div class="col-md-12">
                    @if($resultFlag == 'success')
                        {{ $message }}
                    @elseif($resultFlag == 'refresh')
                        {{ $message }}
                    @elseif($resultFlag == 'bank_error')
                        خطای بانک: {{ $message }}
                    @else
                        {{ $message }}
                    @endif
                    کد پیگیری: {{ @$trackingCode }}
                    <a href="{{ myRoute('profile.payments.payments') }}">برو به سفارشات</a>
                </div>
            </div>
        </div><!--End off row-->
    </div><!--End off container -->
@endsection

likebot_private/resources/views/pricing.blade.php
@extends('layouts.app')

@section('content')
<div class="container blue-bg">
        <div class="row">
            <div class="main_home">
                <div class="col-md-12">

                    {{ session('message') }}


<section>
                <div class="container">
                    <div class="row">
                        <div class="main_drag roomy-50">
                            <div class="col-md-12">
                                <div class="swiper-container">
                                    <div class="swiper-wrapper">
                                        <div class="swiper-slide" style="background-image:url({{myAsset('images/drag1.png')}})">

                                <div class="home_btns btn-drag">
                                     <p class="like-ok">5k لایک</p>
                                     <p class="prev-text">5k لایک</p>
                                     <p class="price-ok">12000 تومان</p>
                                     <p class="prev-text">12000 تومان</p>
                                                                     <a href="" class="btn btn-danger ">انتخاب کنید</a>
                                </div>
                                        </div>
                                                                                <div class="swiper-slide" style="background-image:url({{myAsset('images/drag2.png')}})">

                                                                        <div class="home_btns btn-drag">
                                                                             <p class="like-ok">10k لایک</p>
                                                                             <p class="prev-text">10k لایک</p>
                                                                              <p class="price-ok">21000 تومان</p>
                                                                              <p class="prev-text">21000 تومان</p>
                                                                                                             <a href="" class="btn btn-danger ">انتخاب کنید</a>
                                                                        </div>
                                                                                </div>
                                        <div class="swiper-slide"style="background-image:url({{myAsset('images/drag3.png')}})">
                                                 <div class="home_btns btn-drag">
                                                      <p class="like-ok">25k لایک</p>
                                                      <p class="prev-text">25k لایک</p>
                                                      <p class="price-ok">49000 تومان</p>
                                                      <p class="prev-text">49000 تومان</p>
                                                                     <a href="" class="btn btn-danger ">انتخاب کنید</a>
                                </div>
                                        </div>

             <div class="swiper-slide" style="background-image:url({{myAsset('images/drag4.png')}})">
                                                 <div class="home_btns btn-drag">
                                                   <p class="like-ok">50k لایک</p>
                                                   <p class="prev-text">50k لایک</p>
                                                    <p class="price-ok">89000 تومان</p>
                                                    <p class="prev-text">89000 تومان</p>
                                                                     <a href="" class="btn btn-danger ">انتخاب کنید</a>
                                </div>
                                        </div>


             <div class="swiper-slide" style="background-image:url({{myAsset('images/drag5.png')}})">
                                                 <div class="home_btns btn-drag">
                                                 <p class="like-ok">100k لایک</p>
                                                 <p class="prev-text">100k لایک</p>
                                                 <p class="price-ok">159000 تومان</p>
                                                 <p class="prev-text">159000 تومان</p>
                                                                     <a href="" class="btn btn-danger ">انتخاب کنید</a>
                                </div>
                                        </div>


                                    </div>
                                    <!-- If we need navigation buttons -->
                                    <div class="swiper-button-prev"></div>
                                    <div class="swiper-button-next"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>










                    <form action="{{ route('pricing.apply') }}" method="post">
                        {{ csrf_field() }}
                        @foreach($plans as $key => $plan)
                            @php
                                $discountId = $plan['discount_id'];
                                $likes = $plan['likes'];
                                $price = $plan['price'];
                                $discountDescription = '';
                                $discount = $discounts[$discountId];
                                if ($discountId > 0 && $discount &&
                                        (
                                            ($discount['price'] > 0 && $discount['price'] < $plan['price']) ||
                                            ($discount['likes'] > 0 && $discount['likes'] > $plan['likes'])
                                        )
                                    )  {
                                    $discountDescription = $discount['description'];
                                    $likes = $plan['likes'].(($discount['likes'] > 0 && $discount['likes'] > $plan['likes']) ? '/'.$discount['likes'] : '');
                                    $price = $plan['price'].(($discount['price'] > 0 && $discount['price'] < $plan['price']) ? '/'.$discount['price'] : '');
                                }
                            @endphp
                            {{-- <input type="hidden" name="planId" value="{{ $key }}"> --}}
                            <input type="radio" name="planId" value="{{ $key }}">
                            likes: {{ $likes }}
                            price: {{ $price }}
                            {{ $discountDescription }}
                        @endforeach
                        <button type="submit">Send</button>
                    </form>

                </div>
            </div>
        </div><!--End off row-->
    </div><!--End off container -->
@endsection